### ISSUE TITLE
Subscriptions get SIGSEGV / invalid memory address or nil pointer dereference error on v2.0.0-rc.1 release

### ISSUE THREAD

**Issue by BenjaminYong** [wundergraph/graphql-go-tools#736]
Hi @devsergiy 

Thanks for helping with the [v2.0.0-rc.1](https://github.com/wundergraph/graphql-go-tools/releases/tag/v2.0.0-rc.1) release to help with the [v2 import errors issue](https://github.com/wundergraph/graphql-go-tools/issues/716).

Unfortunately, with this update, my GraphQL subscriptions are no longer working following the [v2 federation gateway example](https://github.com/wundergraph/graphql-go-tools/tree/v1.67.0/v2/examples/federation/gateway)

Queries and mutations are working fine, but any subscriptions give me this error now (subs from both my subgraphs):

```
2024-01-30T11:58:21.981+1100    INFO    abstractlogger@v0.0.4/zap.go:68 logger initialized
2024-01-30T11:58:22.187+1100    INFO    abstractlogger@v0.0.4/zap.go:68 running on default port
2024-01-30T11:58:22.187+1100    INFO    abstractlogger@v0.0.4/zap.go:68 Listening       {"add": "0.0.0.0:8081"}
Access Playground on: http://localhost:8081/playground
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x1049d4874]

goroutine 15 [running]:
github.com/wundergraph/graphql-go-tools/v2/pkg/internal/xcontext.detachedContext.Value(...)
        /Users/byong/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.3/pkg/internal/xcontext/xcontext.go:23
context.value({0x10539d328?, 0x14000602460?}, {0x1052a5f00?, 0x105ac0620})
        /usr/local/go/src/context/context.go:782 +0x2b4
context.(*cancelCtx).Value(0x0?, {0x1052a5f00?, 0x105ac0620?})
        /usr/local/go/src/context/context.go:430 +0x7c
net/http/httptrace.ContextClientTrace(...)
        /usr/local/go/src/net/http/httptrace/trace.go:25
net/http.(*Transport).roundTrip(0x105a821a0, 0x1400022a300)
        /usr/local/go/src/net/http/transport.go:516 +0xac
net/http.(*Transport).RoundTrip(0x14000011540?, 0x105396688?)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x1c
net/http.send(0x1400022a300, {0x105396688, 0x105a821a0}, {0x104712f90?, 0x8?, 0x0?})
        /usr/local/go/src/net/http/client.go:260 +0x4e0
net/http.(*Client).send(0x1400015c7e0, 0x1400022a300, {0x1400013f298?, 0x1047498c0?, 0x0?})
        /usr/local/go/src/net/http/client.go:181 +0x9c
net/http.(*Client).do(0x1400015c7e0, 0x1400022a300)
        /usr/local/go/src/net/http/client.go:724 +0x6f4
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:590
nhooyr.io/websocket.handshakeRequest({0x10539d1a0, 0x1400007e320}, {0x1400048c540?, 0x1044d7740?}, 0x1400007e370, 0x0, {0x14000238168, 0x18})
        /Users/byong/go/pkg/mod/nhooyr.io/websocket@v1.8.10/dial.go:206 +0x7a4
nhooyr.io/websocket.dial({0x10539d1a0?, 0x1400007e320?}, {0x1400048c540, 0x19}, 0x1400013f868?, {0x0, 0x0})
        /Users/byong/go/pkg/mod/nhooyr.io/websocket@v1.8.10/dial.go:128 +0x1ec
nhooyr.io/websocket.Dial(...)
        /Users/byong/go/pkg/mod/nhooyr.io/websocket@v1.8.10/dial.go:106
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/datasource/graphql_datasource.(*SubscriptionClient).newWSConnectionHandler(0x1400010a5a0, {0x10539d1a0, 0x1400007e320}, {{0x1400048c540, 0x19}, {0x0, 0x0, 0x0}, {{0x1400003e370, 0x48}, ...}, ...})
        /Users/byong/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.3/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go:271 +0x100
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/datasource/graphql_datasource.(*SubscriptionClient).subscribeWS(0x1400010a5a0, 0x1400001e000, {{0x1400048c540, 0x19}, {0x0, 0x0, 0x0}, {{0x1400003e370, 0x48}, {0x0, ...}, ...}, ...}, ...)
        /Users/byong/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.3/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go:189 +0x224
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/datasource/graphql_datasource.(*SubscriptionClient).Subscribe(0x104a0290c?, 0x90?, {{0x1400048c540, 0x19}, {0x0, 0x0, 0x0}, {{0x1400003e370, 0x48}, {0x0, ...}, ...}, ...}, ...)
        /Users/byong/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.3/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go:117 +0x88
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/datasource/graphql_datasource.(*SubscriptionSource).Start(0x14000602320, 0x1400015c750?, {0x140009d2180, 0x115, 0x180}, {0x10539b1c8, 0x1400015c720})
        /Users/byong/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.3/pkg/engine/datasource/graphql_datasource/graphql_datasource.go:1806 +0xd8
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve.(*Resolver).handleAddSubscription(0x1400010fcc0, 0xd411dd2e36a9f1b6, 0x14000780180)
        /Users/byong/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.3/pkg/engine/resolve/resolve.go:284 +0x350
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve.(*Resolver).handleEvent(0x140000706f8?, {0xd411dd2e36a9f1b6, {0x0, 0x0, 0x0}, 0x3, {0x0, 0x0, 0x0}, 0x14000780180})
        /Users/byong/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.3/pkg/engine/resolve/resolve.go:219 +0xc4
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve.(*Resolver).handleEvents(0x1400010fcc0)
        /Users/byong/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.3/pkg/engine/resolve/resolve.go:211 +0x94
created by github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve.New in goroutine 50
        /Users/byong/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.3/pkg/engine/resolve/resolve.go:105 +0x27c
exit status 2
```

When debugging, it looks to be trying to access a nil parent field in the xcontext package:
`func (v detachedContext) Value(key interface{}) interface{} { return v.parent.Value(key) }`

Any ideas? Your help would be appreciated, thanks!

**Comment by devsergiy** [comment]
Hi @BenjaminYong 

federation example was updated to use latest v2 code
