### ISSUE TITLE
Federation example not working since upgrading to newer version than rc.32

### ISSUE THREAD

**Issue by argoyle** [wundergraph/graphql-go-tools#806]
After Renovate upgraded my lib-version to anything newer than rc.32 I get a nil pointer dereference:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102bd3218]

goroutine 14 [running]:
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve.(*Resolver).handleRemoveSubscription(0x140060a1c20, {0x1, 0x0, 0x1})
        /Users/argoyle/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.34/pkg/engine/resolve/resolve.go:430 +0x2b8
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve.(*Resolver).handleEvent(0x140060a1c20, {0x36b32dfcbdadb505, {0x1, 0x0, 0x1}, 0x4, {0x0, 0x0, 0x0}, 0x0})
        /Users/argoyle/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.34/pkg/engine/resolve/resolve.go:323 +0xfc
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve.(*Resolver).handleEvents(0x140060a1c20)
        /Users/argoyle/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.34/pkg/engine/resolve/resolve.go:313 +0x128
created by github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve.New in goroutine 26
        /Users/argoyle/go/pkg/mod/github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.34/pkg/engine/resolve/resolve.go:153 +0x64c
```

It looks like the ctx.Context() is nil.

**Comment by argoyle** [comment]
Hmmm, maybe I was wrong actually and had some other change locally. Seems to work with rc.40 again at least. Closing.
